# Generated by Django 4.2.7 on 2024-02-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_image_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cover',
        ),
        migrations.AddField(
            model_name='card',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='shop/pic'),
        ),
    ]
